#!/usr/bin/env node
/**
 * Regenerates docs/assets/library.js and GEM_INSTRUCTIONS.md from the repo's
 * markdown, so the studio and the paste-in Gem bundle never drift from the
 * source of truth in /templates, /examples and /.gem.
 *
 * Usage: npm run build   (or: node scripts/build-library.mjs)
 * Add --check to fail instead of writing when output is stale (used by CI).
 */
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const FILE_NAMES = ['title.md', 'description.md', 'lyrics.md', 'cover-art.md'];
const CHECK_ONLY = process.argv.includes('--check');

const read = (...p) => readFileSync(join(ROOT, ...p), 'utf8');

function readPack(dir) {
  const pack = {};
  for (const name of FILE_NAMES) {
    const path = join(dir, name);
    if (!existsSync(path)) throw new Error(`missing ${path}`);
    pack[name] = readFileSync(path, 'utf8').trimEnd();
  }
  return pack;
}

/** Pull "# Title\nSomething" out of a title.md, falling back to the slug. */
function titleOf(pack, slug) {
  const line = (pack['title.md'].split('\n').find((l) => l.trim() && !l.startsWith('#')) || '').trim();
  return line || slug;
}

/** First line of the Description body, for the library card blurb. */
function blurbOf(pack) {
  const lines = pack['description.md'].split('\n');
  const start = lines.findIndex((l) => l.startsWith('# Description'));
  return (lines.slice(start + 1).find((l) => l.trim()) || '').trim();
}

/** Read the Sonic Architecture bullets into a flat {Tempo: '96 BPM', ...} map. */
function specOf(pack) {
  const spec = {};
  for (const line of pack['description.md'].split('\n')) {
    const m = line.match(/^-\s+\*\*(.+?):\*\*\s*(.+)$/);
    if (m) spec[m[1]] = m[2].trim();
  }
  return spec;
}

const templates = readPack(join(ROOT, 'templates'));

const examplesDir = join(ROOT, 'examples');
const examples = readdirSync(examplesDir)
  .filter((slug) => statSync(join(examplesDir, slug)).isDirectory())
  .sort()
  .map((slug) => {
    const pack = readPack(join(examplesDir, slug));
    return { slug, title: titleOf(pack, slug), blurb: blurbOf(pack), spec: specOf(pack), files: pack };
  });

const gem = {
  role: read('.gem', 'role.md').trimEnd(),
  rules: read('.gem', 'rules.md').trimEnd(),
  task: read('.gem', 'tasks', 'song.md').trimEnd()
};

const instructions = [
  '<!-- GENERATED by scripts/build-library.mjs from .gem/ — edit those files, not this one. -->',
  '# Gem Instructions (paste-in bundle)',
  '',
  'Paste everything below into your Gem\'s **Instructions** box. It is the',
  'concatenation of `.gem/role.md`, `.gem/rules.md` and `.gem/tasks/song.md`.',
  '',
  '---',
  '',
  gem.role,
  '',
  gem.rules,
  '',
  gem.task,
  ''
].join('\n');

const library = [
  '/* GENERATED by scripts/build-library.mjs — do not edit by hand.',
  '   Source of truth: /templates, /examples, /.gem. Run `npm run build` after changing them. */',
  '',
  'window.GEM_LIBRARY = ' + JSON.stringify({ templates, examples, gem, instructions }, null, 2) + ';',
  ''
].join('\n');

const outputs = [
  ['docs/assets/library.js', library],
  ['GEM_INSTRUCTIONS.md', instructions]
];

let stale = false;
for (const [rel, content] of outputs) {
  const path = join(ROOT, rel);
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (current === content) continue;
  stale = true;
  if (CHECK_ONLY) {
    console.error(`✗ ${rel} is out of date — run \`npm run build\` and commit the result.`);
  } else {
    writeFileSync(path, content);
    console.log(`✓ wrote ${rel}`);
  }
}

if (CHECK_ONLY && stale) process.exit(1);
if (!stale) console.log('✓ generated files already up to date');
console.log(`  ${examples.length} example pack(s), ${FILE_NAMES.length} templates`);
